version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn install --frozen-lockfile
      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: [.]
  lint:
    docker:
        - image: circleci/node:8-browsers
    steps:
      - attach_workspace: { at: . }
      - restore_cache:
          key: deps-{{ checksum "yarn.lock" }}
      - run:
          name: Run Linter (not enforcing for now)
          command: yarn lint

  test:
    docker:
        - image: circleci/node:8-browsers
    steps:
      - attach_workspace: { at: . }
      - restore_cache:
          key: deps-{{ checksum "yarn.lock" }}
      - run:
          name: Run Tests
          command: yarn test


workflows:
  version: 2
  test:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup