version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - git ls-remote https://github.com/segmentio/analytics.js-integrations refs/heads/master | > shas
      - run:
          name: Determine which projects have changed and trigger the builds
          command: |
            # Identify modified directories
            LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/master?filter=completed&limit=1"
            MASTER_URL="https://github.com/segmentio/analytics.js-integrations/commits?branch=master&limit=1"

            echo -e "URL ${LAST_SUCCESSFUL_BUILD_URL}"
            echo -e "Shas ${shas}"

            echo -e "URL ${MASTER_URL}"
            LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`

            #Commit on this branch to master branch (currently going to last successful on circleci which from 2018)
            COMMITS="${CIRCLE_SHA1}..${LAST_SUCCESSFUL_COMMIT}"
            echo -e "these commits ${COMMITS}"
            git diff --name-only $COMMITS | cut -d/ -f1 | sort -u > projects
            echo -e "Modified directories:\n`cat projects`\n"

            # If modified directories contain yarn, operations, compiler, buildkite directores, exit
            buildall=0
            for project in `cat projects`; do
              if [[ ${project} =~ "yarn" || ${project} =~ ".buildkite" ]]; then
                buildall=1
                echo -e "Warning. Dependencies or internal configs have change detected."
                exit 1
              fi
            done
      - restore_cache:
          key: deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn install --frozen-lockfile
      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: [.]
  lint:
    docker:
        - image: circleci/node:8-browsers
    steps:
      - attach_workspace: { at: . }
      - restore_cache:
          key: deps-{{ checksum "yarn.lock" }}
      - run:
          name: Run Linter (not enforcing for now)
          command: yarn lint

  test:
    docker:
        - image: circleci/node:8-browsers
    steps:
      - attach_workspace: { at: . }
      - restore_cache:
          key: deps-{{ checksum "yarn.lock" }}
      - run:
          name: Run Tests
          command: yarn test


workflows:
  version: 2
  test:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup